### ISSUE TITLE
Communication Test with Android

### ISSUE THREAD

**Issue by kyu9341** [wjrmffldrhrl/UleungCare#3]
안드로이드에서 volley를 이용하여 Django로 통신하는 부분에서 지속적인 에러 발생

Django 에러 코드
[22/Sep/2019 11:09:00] code 400, message Bad request version ('À')
[22/Sep/2019 11:09:00] You're accessing the development server over HTTPS, but it only supports HTTP.
안드로이드에서 송신방식이 HTTP가 아니어서 발생하는 오류로 추정

안드로이드 에러 코드
javax.net.ssl.SSLHandshakeException: Handshake failed:

java에서 https로 remote site에 연결한 경우 발생하는 exception
원인
 $JAVA_HOME/jre/lib/security 폴더(인증기관 인증서 목록(keystore)) 내에 접속하고자 하는 IP or HOST의 SSL 서버에서 유효한 인증서가 존재하지 않을 경우 발생함.
참고 : https://blog.geun.kr/79

**Comment by kyu9341** [comment]
url을 https:~에서 http로 변경하고 수행 -> 안드로이드에서 E/Volley: [302] BasicNetwork.performRequest: Unexpected response code 400 for http://10.0.2.2:8000/uleung/androidControl/ 에러 발생

Django에서 Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS. 에러메시지 발생

**Comment by kyu9341** [comment]
https://stackoverflow.com/questions/40582423/invalid-http-host-header 참고
Django의 setting.py 에 ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '127.0.0.1'] 설정
-> 통신성공

**Comment by wjrmffldrhrl** [comment]
plz close issue
